source 'https://github.com/cosmos33/MMSpecs.git'

platform :ios, '11.0'

install! 'cocoapods',
:deterministic_uuids => false,
:share_schemes_for_development_pods => true,
:generate_multiple_pod_projects => true

target 'EngineDemoiOS' do
  pod 'MMXEngineBase',    '4.5.1.ssl'           #必要
  pod 'XESceneKit',       '4.5.1.20211025.1123' #必要

  pod 'XEngineAudio',     '4.5.1.20211025.1123' #可选
  pod 'XEngineLua',       '4.5.1.20211025.1123' #可选
  pod 'XEnginePhysics',   '4.5.1.20211025.1123' #可选
  pod 'XEngineUI',        '4.5.1.20211025.1123' #可选
end
