source 'https://github.com/cosmos33/MMSpecs.git'

platform :ios, '11.0'

install! 'cocoapods',
:deterministic_uuids => false,
:share_schemes_for_development_pods => true,
:generate_multiple_pod_projects => true

target 'EngineDemoiOS' do
  
  #引擎依赖👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇
  pod 'MMXEngineBase',    '4.5.2.ssl'           #必要
  pod 'XESceneKit',       '4.5.3.20220413.1749' #必要

  pod 'XEngineAudio',     '4.5.3.20220413.1749' #可选
  pod 'XEngineLua',       '4.5.3.20220413.1749' #可选
  pod 'XEnginePhysics',   '4.5.3.20220413.1749' #可选
  pod 'XEngineUI',        '4.5.3.20220413.1749' #可选
  #引擎依赖👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆
  
  #重要提示‼️‼️‼️‼️‼️‼️‼️‼️
  #DEMO中使用的引擎版本不一定是最新的，上线时请联系相关人员进行确认‼️
  #重要提示‼️‼️‼️‼️‼️‼️‼️‼️
  
end
